### ISSUE TITLE
License under MIT or clarify current limitations

### ISSUE THREAD

**Issue by niello** [cegui/ceed-cpp#86]
Now CEED is GPL-3. Why exactly this? What limitation it implies? What is intended by CEED devs and what is a 3rd-party requirement. Is there a good reason for not making it MIT?

**Comment by niello** [comment]
@Ident , do you have thoughts about this?

**Comment by Ident** [comment]
Changing the license is difficult, it requires us to basically ask all contributors to accept their code is now under a new license. For me personally MIT license is fine for anything i ever did for CEGUI repos.

Regarding why it is the license it is in the first place: no idea, @mpreisler  or @pauldtuk  might know more

**Comment by pauldtuk** [comment]
Somewhat irrelevant historical information: CEGUI itself used to be LGPL, this was changed to MIT and was indeed somewhat of a headache due to the reasons stated by @Ident. Some parts needed to be rewritten entirely due to original authors not responding to contact regarding that change in license.

I think for a library, a more permissive license makes sense (which is why the above change was eventually made). However, I'm not sure of what, if any, benefit exists for an end user tool to be MIT licensed as opposed to GPL - though it's certainly possible that I've totally missed some obvious reasoning.

All this being said, I don't really have a dog in this fight - I have zero code contributions to ceed-cpp :)

**Comment by mpreisler** [comment]
Hi, sorry for not being responsive earlier. I myself am fine with changing the license to MIT. There are more contributors to the original codebase but @Ident and myself are the most significant.

As @pauldtuk said, for an end-user tool it probably does not matter and there are no significant benefits in changing that to MIT. There is one consideration, if you change ceed-cpp to MIT people might create closed off forks without giving back patches. Not sure if that matters to you.
